baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "the stupidest thing..."
theme = "hugo-lithium-theme"
googleAnalytics = ""
disqusShortname = "kbroman-blog"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "about"
    url = "/about/"
[[menu.main]]
    name = "github"
    url = "https://github.com/kbroman"
[[menu.main]]
    name = "twitter"
    url = "https://twitter.com/kwbroman"
[[menu.main]]
    name = "web"
    url = "http://kbroman.org"

[params]
    description = "Karl Broman's blog: The stupidest thing... statistics, genetics, programming, academics."
    disqusURL = "http://kbroman.org/blog"
    fullURL = "http://kbroman.org/blog"
    githubContentURL = "https://github.com/kbroman/blog/edit/source/content/"
    customCSS = ["css/custom.css"]

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.10.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    [params.logo]
    url = "karl.png"
    width = 50
    height = 50
    alt = "Logo"
